name: Swift

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        lfs: 'true'
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: Install Dependencies
      run: |
        cd ButterfliesOfGreece
        pod install --repo-update
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        workspace: ButterfliesOfGreece.xcworkspace
        scheme: ButterfliesOfGreece
        lint: false 
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'
        additional_lint_params: --private
    - name: Build in folder
      run: xcodebuild -workspace 'ButterfliesOfGreece/ButterfliesOfGreece.xcworkspace' -scheme 'ButterfliesOfGreece' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      run: xcodebuild clean test -workspace 'ButterfliesOfGreece/ButterfliesOfGreece.xcworkspace' -scheme "ButterfliesOfGreece" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"



