name: Swift

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Install Dependencies
      run: |
        cd ButterfliesOfGreece
        rm -Rf Pods
        pod install
      shell: bash
    - name: Build in folder
      run: xcodebuild -workspace 'ButterfliesOfGreece/ButterfliesOfGreece.xcworkspace' -scheme 'ButterfliesOfGreece' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      run: xcodebuild clean test -workspace 'ButterfliesOfGreece/ButterfliesOfGreece.xcworkspace' -scheme "ButterfliesOfGreece" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"



