name: Swift

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build in folder
      run: ButterfliesOfGreece/swift build -v
    - name: Run tests
      run: ButterfliesOfGreece/swift test -v
