name: Swift

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build in folder
      run: xcodebuild -project 'ButterfliesOfGreece/ButterfliesOfGreece.xcodeproj' -scheme 'ButterfliesOfGreece' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
#    - name: Run tests
#      working-directory: ButterfliesOfGreeceTests
#      run: ButterfliesOfGreece/swift test -v

